# Panel_b for Norman2019: heatmaps of TF activities, Z and Z_hat matrices, T-Mex matrices
#
# Prerequisites: run Norman2019_Panel_b_prep.ipynb first to generate the .npy files.

rm(list = ls())
library(ComplexHeatmap)
library(latex2exp)
library(reticulate)
library(clue)
library(igraph)
source('partial_mcc_matrix.R')
np <- import("numpy")

# ── Control panel ──────────────────────────────────────────────
pct         <- 40
gamma       <- '1p1'
num_cells   <- 1000
current_folder <- file.path(dirname(rstudioapi::getSourceEditorContext()$path), '../../../results/figures/main/Fig1')
setwd(current_folder)

# Community colours — SAME order and palette as Panel_a (community index → colour)
color_pool <- c('yellow', 'darkmagenta', 'cyan', 'red3', 'green3',
                'blue3', 'violet', 'orange')
global_color <- 'grey50'   # colour for the global TF factor (last column)
greys <- c('grey10', 'grey15', 'grey20', 'grey25', 
           'grey30', 'grey35', 'grey40', 'grey45') # colors for the z_hat


res_folder <- file.path(current_folder, 'Norman2019/Panel_b')
dir.create(res_folder, showWarnings = FALSE, recursive = TRUE)

# ── Load matrices ──────────────────────────────────────────────
# Generated by Norman2019_Panel_b_prep.ipynb.
# All four matrices share the same number of columns: n_factors = n_comm + 1.
# Column order: [comm_0, comm_1, ..., comm_(n_comm-1), global]
load_npy <- function(path) {
  tmp <- np$load(path, allow_pickle = TRUE)
  mat <- py_to_r(tmp)
  if (is.list(mat)) mat <- do.call(rbind, mat)
  as.matrix(mat)
}

tf_activities_matrix <- load_npy(file.path(res_folder, 'Partial_MCC_A.npy'))
z_matrix             <- load_npy(file.path(res_folder, 'Partial_MCC_BX.npy'))
z_hat_matrix         <- load_npy(file.path(res_folder, 'Partial_MCC_B.npy'))
a_matrix             <- load_npy(file.path(res_folder, 'Partial_MCC_X.npy'))

# n_factors = n_comm + 1 (last column is always the global factor)
num_factors <- ncol(tf_activities_matrix)
n_comm      <- num_factors - 1L
cat('n_comm:', n_comm, '  n_factors (incl. global):', num_factors, '\n')

# ── Colour vectors: community colours + grey for global ────────
# These are used identically in Panel_a for communities 0..(n_comm-1).
factor_colors <- c(color_pool[seq_len(n_comm)], global_color)
factor_labels <- c(paste0('CF ', seq_len(n_comm)), 'Global')
grey_colors <- c(greys[seq_len(n_comm)], global_color)
names(factor_colors) <- factor_labels
names(grey_colors)   <- factor_labels

# Column titles for heatmaps
tfa_titles  <- c(TeX(paste0('$TFA_', seq_len(n_comm), '$')),  TeX('$TFA_{global}$'))
z_titles    <- c(TeX(paste0('$Z_',   seq_len(n_comm), '$')),  TeX('$Z_{global}$'))
zhat_titles <- c(TeX(paste0('$\\hat{Z}_', seq_len(num_factors), '$')))

# ── Cell selection ─────────────────────────────────────────────
cell_rank_product <- log2(rank(apply(tf_activities_matrix, 1, sd)) + 1) *
                     log2(rank(apply(z_matrix, 1, sd)) + 1)
to_select <- order(cell_rank_product, decreasing = TRUE)[1:num_cells]

# ── Shared column annotation builder ──────────────────────────
make_col_ann <- function(colors_vec = factor_colors,
                          labels_vec = factor_labels,
                          which_side = 'col') {
  cc <- colors_vec; names(cc) <- labels_vec
  if (which_side == 'col')
    HeatmapAnnotation(CF = labels_vec, col = list(CF = cc),
                      show_annotation_name = FALSE, show_legend = FALSE)
  else
    HeatmapAnnotation(CF = labels_vec, col = list(CF = cc),
                      show_annotation_name = FALSE, show_legend = FALSE, which = 'row')
}

col_ann      <- make_col_ann()                        # A and Z heatmaps
col_ann_grey <- make_col_ann(grey_colors,             # Z_hat heatmap
                              factor_labels, "col")

# ── Heatmaps ───────────────────────────────────────────────────
suppressMessages({

tf_activities_hm <- Heatmap(
  tf_activities_matrix[to_select, , drop = FALSE],
  column_split        = seq_len(num_factors),
  column_title        = tfa_titles,
  show_heatmap_legend = FALSE,
  top_annotation      = col_ann,
  cluster_rows        = FALSE, cluster_columns = FALSE)

z_hm <- Heatmap(
  z_matrix[to_select, , drop = FALSE],
  column_split        = seq_len(num_factors),
  column_title        = z_titles,
  show_heatmap_legend = FALSE,
  top_annotation      = col_ann,
  cluster_rows        = FALSE, cluster_columns = FALSE)

z_hat_hm <- Heatmap(
  z_hat_matrix[to_select, , drop = FALSE],
  column_split        = seq_len(num_factors),
  column_title        = zhat_titles,
  show_heatmap_legend = FALSE,
  top_annotation      = col_ann_grey,
  cluster_rows        = FALSE, cluster_columns = FALSE)

})

for (nm in c('heatmap_tf_activities', 'heatmap_z', 'heatmap_z_hat')) {
  hm <- switch(nm,
    heatmap_tf_activities = tf_activities_hm,
    heatmap_z             = z_hm,
    heatmap_z_hat         = z_hat_hm)
  png(file.path(res_folder, paste0(nm, '.png')), height = 2100, width = 2100, res = 300)
  plot(hm)
  dev.off()
  svg(file.path(res_folder, paste0(nm, '.svg')), height = 7, width = 7)
  plot(hm)
  dev.off()
}

# ── A-matrix bipartite graph ───────────────────────────────────
# Rows (left)  = Z_hat factors  — coloured by community / grey for global
# Cols (right) = Z latent dims  — same colour scheme
row_labels <- paste0('hat_Z_', seq_len(num_factors))   # hat_Z_1 .. hat_Z_7
col_labels <- c(paste0('Z_', seq_len(n_comm)), 'Z_Global')

edges   <- which(a_matrix != 0, arr.ind = TRUE)
edge_df <- data.frame(
  from   = row_labels[edges[, 1]],
  to     = col_labels[edges[, 2]],
  weight = a_matrix[edges])

g <- graph_from_data_frame(edge_df, directed = FALSE,
                            vertices = c(row_labels, col_labels))
V(g)$type  <- c(rep(0, num_factors), rep(1, num_factors))
V(g)$color <- c(grey_colors[seq_len(num_factors)],    # left: Z_hat — greys
                factor_colors[seq_len(num_factors)])  # right: Z    — community colours
V(g)$shape <- 'square'
V(g)$size  <- 30

y_pos         <- seq(1, 0, length.out = num_factors)
layout_manual <- rbind(cbind(x = -1, y = y_pos),
                        cbind(x =  1, y = y_pos))
rownames(layout_manual) <- c(row_labels, col_labels)

wts      <- E(g)$weight
wts_norm <- (abs(wts) - min(abs(wts))) / (max(abs(wts)) - min(abs(wts)) + 1e-9)
E(g)$width <- 1 + 4 * wts_norm
E(g)$color <- ifelse(wts > 0,
                     rgb(1, 0.1, 0.1, alpha = wts_norm),
                     rgb(0.1, 0.1, 1,  alpha = wts_norm))

plot_a_matrix <- function() {
  sz <- 4 + num_factors / 5
  igraph::plot.igraph(g, layout = layout_manual[V(g)$name, ],
                      vertex.label = NA,
                      edge.width   = E(g)$width,
                      edge.color   = E(g)$color,
                      margin = 0.2)
  coords      <- layout_manual[V(g)$name, ]
  coords[, 2] <- (2 * (coords[, 2] - min(coords[, 2])) /
                    (max(coords[, 2]) - min(coords[, 2]))) - 1
  offset_x <- 0.4
  for (i in seq_along(V(g))) {
    nm <- V(g)$name[i]
    x  <- coords[i, 1]
    y  <- coords[i, 2]
    if (V(g)$type[i] == 0) {
      k   <- sub('hat_Z_', '', nm, fixed = TRUE)   # "1".."7"
      lbl <- TeX(paste0('$\\hat{Z}_{', k, '}$'))
      text(x - offset_x, y, labels = lbl)
    } else {
      if (nm == 'Z_Global') {
        lbl <- TeX('$Z_{Global}$')
      } else {
        k   <- sub('Z_', '', nm, fixed = TRUE)
        lbl <- TeX(paste0('$Z_{', k, '}$'))
      }
      text(x + offset_x, y, labels = lbl)
    }
  }
}

svg(file.path(res_folder, 'a_matrix.svg'),
    height = 4 + num_factors / 5, width = 4 + num_factors / 5)
plot_a_matrix()
dev.off()
png(file.path(res_folder, 'a_matrix.png'),
    height = 2100, width = 2100, res = 300)
plot_a_matrix()
dev.off()

# ── T-Mex heatmap helper ───────────────────────────────────────
plot_tmex_heatmap <- function(mat, row_ann, col_ann, row_titles, col_titles,
                               tmex_val, out_path) {
  row_max_idx <- apply(abs(mat), 1, which.max)
  ht <- Heatmap(mat,
                row_split    = seq_len(nrow(mat)),
                row_title    = row_titles,
                column_split = seq_len(ncol(mat)),
                column_title = col_titles,
                cluster_rows = FALSE, cluster_columns = FALSE,
                show_row_names = FALSE, show_column_names = FALSE,
                left_annotation = row_ann,
                top_annotation  = col_ann,
                show_heatmap_legend = FALSE,
                cell_fun = function(j, i, x, y, w, h, fill) {
                  if (j == row_max_idx[i])
                    grid.text(sprintf('%.3f', mat[i, j]), x, y,
                              gp = gpar(fontsize = 10, fontface = 'bold'))
                })
  sz <- 4 + max(nrow(mat), ncol(mat)) / 5
  svg(out_path, height = sz, width = sz)
  draw(ht, column_title    = paste0('T-Mex = ', round(tmex_val, 3)),
       column_title_side   = 'bottom',
       column_title_gp     = gpar(fontsize = 20))
  dev.off()
}

# ── T-Mex: A vs Z (all factors, including global) ─────────────
p_mcc_z <- partial_mcc_matrix(tf_activities_matrix, z_matrix)
cat('T-Mex (A vs Z):', round(mean(diag(p_mcc_z)), 3), '\n')

plot_tmex_heatmap(
  p_mcc_z,
  make_col_ann(which_side = 'row'),
  make_col_ann(which_side = 'col'),
  tfa_titles, z_titles,
  mean(diag(p_mcc_z)),
  file.path(res_folder, 'tmex_z.svg'))

# ── T-Mex: A vs Z_hat (all factors, including global) ─────────
p_mcc_zhat <- partial_mcc_matrix(tf_activities_matrix, z_hat_matrix)
cat('T-Mex (A vs Z_hat):', round(mean(diag(p_mcc_zhat)), 3), '\n')

plot_tmex_heatmap(
  p_mcc_zhat,
  make_col_ann(which_side = 'row'),
  make_col_ann(grey_colors, factor_labels, 'col'),
  tfa_titles, zhat_titles,
  mean(diag(p_mcc_zhat)),
  file.path(res_folder, 'tmex_z_hat.svg'))

# ── T-Mex: A vs Z_hat, optimal permutation ────────────────────
res_opt <- optimal_partial_mcc_matrix(tf_activities_matrix, z_hat_matrix)
cat('T-Mex optimal (A vs Z_hat*):', round(res_opt$mean_partial_mcc, 3), '\n')

# Permute the column colours and titles to follow the optimal assignment
perm_colors      <- factor_colors[res_opt$permutation]
perm_grey_colors <- grey_colors[res_opt$permutation]
perm_labels      <- factor_labels[res_opt$permutation]
perm_titles      <- zhat_titles[res_opt$permutation]

plot_tmex_heatmap(
  res_opt$matrix,
  make_col_ann(which_side = 'row'),
  make_col_ann(perm_grey_colors, perm_labels, 'col'),
  tfa_titles, perm_titles,
  res_opt$mean_partial_mcc,
  file.path(res_folder, 'tmex_z_hat_optimal.svg'))

cat('\nAll Panel_b figures saved to', res_folder, '\n')
